### ISSUE TITLE
Urduhack new API Roadmap 

### ISSUE THREAD

**Issue by akkefa** [urduhack/urduhack#114]
# Roadmap to introduce new API for Urduhack

### Core features:
1. Using https://universaldependencies.org CoNLL-U Format for data generation and model training. we will save our datasets in CoNLL-U format. 
2. Introduce a new API which represents  CoNLL-U at the abstract level.

### Tasks:

- [ ] Complete understanding for https://universaldependencies.org CoNLL-U Format.
- [ ] Develop a wrapper API to load | convert data from CoNLL-U Format.
- [ ] Introducing a new module model which will hold all ML models API.
- [ ] Urduhack will support two core API functional and dynamic.

**We will do couples of meetup to finalize things**
Please join the FB group.
https://www.facebook.com/groups/238735070390350

@urduhack/ventures 
@urdutext
